---
# yamllint disable rule:line-length
- name: get hardware info
  hosts: all
  gather_facts: false
  tasks:
    - name: Install lshw nvme-cli smartmontools
      become: true
      ansible.builtin.package:
        name:
          - lshw
          - nvme-cli
          - smartmontools
        state: present

    - name: get information
      become: true
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          lshw -short -c system | grep system | grep -v 'PnP device' | awk -F'system' '{print $2}'
          lshw -short -c memory | egrep "System Memory|DIMM" | grep -v empty | awk -F'memory' '{print $2}' | sort | tr -s ' ' | uniq -c
          lshw -short -c cpu | grep processor | awk -F'processor' '{print $2}' | tr -s ' ' | uniq -c
          nvme list -o json | grep ModelNumber | awk -F'"' '{print $4}' | sort | tr -s ' ' | uniq -c || :
          for disk in `find /dev/ -name sg*`;do smartctl -a $disk | grep "User Capacity" -B4 | egrep 'Device Model|Product'; done | awk -F':' '{print $2}' | sort | tr -s ' ' | uniq -c || :
          echo "----------lsblk---------"
          #lsblk -d -o MODEL | tail -n +2 | awk 'NF' | sort | uniq -c # | egrep "sata|sas|nvme"
          lsblk -d -o NAME,MODEL,SERIAL,SIZE | egrep -v "loop[[:digit:]]|zd[[:digit:]]|drbd[[:digit:]]|sr[[:digit:]]"
      args:
        executable: /bin/bash
      register: lshw
      changed_when: false

    - name: Hardware information
      vars:
        msg: |
          {{ lshw.stdout_lines | to_nice_yaml(indent=8, width=1337) }}
      debug:
        msg: "{{ msg.split('\n') }}"
