---
# yamllint disable rule:line-length
- name: get hardware info
  hosts: all
  gather_facts: false
  tasks:
    - name: Install lshw nvme-cli smartmontools
      become: true
      ansible.builtin.package:
        name:
          - lshw
          - nvme-cli
          - smartmontools
        state: present
    - name: get system
      become: true
      ansible.builtin.shell:
        cmd: lshw -short -c system | grep system | grep -v 'PnP device' | awk -F'system' '{print $2}'
      args:
        executable: /bin/bash
      register: lshw_sys
      changed_when: false

    - name: get memory info
      become: true
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          lshw -short -c memory | egrep "System Memory|DIMM" | grep -v empty | awk -F'memory' '{print $2}' | sort | tr -s ' ' | uniq -c
      args:
        executable: /bin/bash
      register: lshw_mem
      changed_when: false

    - name: get CPU info
      become: true
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          lshw -short -c cpu | grep processor | awk -F'processor' '{print $2}' | tr -s ' ' | uniq -c
      args:
        executable: /bin/bash
      register: lshw_cpu
      changed_when: false

    - name: get disk info
      become: true
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          echo 'NVMe disks'
          nvme list -o json | grep ModelNumber | awk -F'"' '{print $4}' | sort | uniq -c
          echo 'sata/sas behind HP HBA'
          set -o pipefail && for disk in `ls /dev/sg*`;do smartctl -a $disk | grep "Device Model" | tr -s ' ' | awk -F':' '{print $2}'; done |sort | uniq -c || echo ""
      args:
        executable: /bin/bash
      register: lshw_dsk
      changed_when: false

    - name: Hardware information
      vars:
        msg: |
          {{ lshw_sys.stdout_lines | to_nice_yaml(indent=8, width=1337) }}
          {{ lshw_cpu.stdout_lines | to_nice_yaml(indent=8, width=1337) }}
          {{ lshw_mem.stdout_lines | to_nice_yaml(indent=8, width=1337) }}
          {{ lshw_dsk.stdout_lines | to_nice_yaml(indent=8, width=1337) }}
      debug:
        msg: "{{ msg.split('\n') }}"
