---
- name: get hardware info
  hosts: all
  gather_facts: true
  tasks:
    - name: install lshw
      become: true
      ansible.builtin.package:
        name: lshw
        state: present
    - name: get memory info
      become: true
      ansible.builtin.shell:
        # yamllint disable-line rule:line-length
        cmd: set -euxo pipefail && lshw -short -c memory | egrep "System Memory|DIMM"
          | grep -v empty | awk -F'memory' '{print $2}' | sort | uniq -c
      args:
        executable: /bin/bash
      register: lshw_mem
      changed_when: false
    - name: get CPU info
      become: true
      ansible.builtin.shell:
        # yamllint disable-line rule:line-length
        cmd: set -euxo pipefail && lshw -short -c cpu | grep processor | awk -F'processor'
          '{print $2}' | uniq -c
      args:
        executable: /bin/bash
      register: lshw_cpu
      changed_when: false

    - name: get disk info
      become: true
      ansible.builtin.shell:
        # yamllint disable-line rule:line-length
        cmd: set -euxo pipefail && fdisk -l | egrep "/dev/sd|/dev/nvm" -A2 | grep "Disk model"
      args:
        executable: /bin/bash
      register: fdisk_hdd
      changed_when: false
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >='20'

    - name: get disk info by lshw
      become: true
      ansible.builtin.shell:
        # yamllint disable-line rule:line-length
        cmd: set -euxo pipefail && lshw -c disk #| grep disk -A3 | grep  product && lshw | grep NVMe -A2 | grep product
      args:
        executable: /bin/bash
      register: lshw_disk
      changed_when: false

    - name: all together
      vars:
        msg: |
          {{ lshw_cpu.stdout_lines | to_nice_json }}
          {{ lshw_mem.stdout_lines | to_nice_json }}
          {{ fdisk_hdd.stdout_lines | to_nice_json }}
          {{ lshw_disk.stdout_lines | to_nice_json }}
      debug:
        msg: "{{ msg.split('\n') }}"
